-- ── DATABASE SCHEMA FOR EDUFLEX ──────────────────────────────────────────────

-- 1. COURSES TABLE
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  description text,
  category text,
  price integer not null default 0,
  duration_hours integer not null default 0,
  level text not null default 'debutant',
  image_url text,
  status text not null default 'publie',
  students_count integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for courses
alter table public.courses enable row level security;

-- Policies for courses
create policy "Allow public read access for courses"
  on public.courses for select
  using (true);

create policy "Allow authenticated users to insert courses"
  on public.courses for insert
  with check (auth.uid() = user_id);

create policy "Allow owners to update their courses"
  on public.courses for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Allow owners to delete their courses"
  on public.courses for delete
  using (auth.uid() = user_id);


-- 2. ENROLLMENTS TABLE
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  course_id bigint not null references public.courses(id) on delete cascade,
  progress_percent integer not null default 0,
  enrolled_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, course_id)
);

-- Enable Row Level Security (RLS) for enrollments
alter table public.enrollments enable row level security;

-- Policies for enrollments
create policy "Allow users to read their own enrollments"
  on public.enrollments for select
  using (auth.uid() = user_id);

create policy "Allow users to enroll themselves"
  on public.enrollments for insert
  with check (auth.uid() = user_id);

create policy "Allow users to update their own progress"
  on public.enrollments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- 3. SEED INITIAL COURSES DATA
insert into public.courses (user_id, title, description, category, price, duration_hours, level, image_url, status, students_count)
values
  (
    '00000000-0000-0000-0000-000000000000', -- Generic system/placeholder UUID
    'Marketing Digital de A à Z',
    'Maîtrisez les leviers du marketing digital : SEO, SEA, Social Media, Emailing et Analytics pour booster votre activité.',
    'Marketing',
    29900,
    25,
    'debutant',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=60',
    'publie',
    145
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Business Management & Stratégie',
    'Apprenez à piloter une entreprise, définir une stratégie de croissance et manager vos équipes avec succès.',
    'Business',
    49900,
    40,
    'intermediaire',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=60',
    'publie',
    89
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'SEO & Création de Contenu',
    'Devenez visible sur Google. Techniques de référencement naturel avancées et rédaction de contenu engageant.',
    'Marketing',
    39900,
    15,
    'intermediaire',
    'https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=800&auto=format&fit=crop&q=60',
    'publie',
    210
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'Excel Avancé : Tableaux & Analyse',
    'Maîtrisez les formules complexes, les TCD, les macros VBA et la visualisation de données sur Microsoft Excel.',
    'Productivité',
    19900,
    12,
    'avance',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60',
    'publie',
    324
  )
on conflict do nothing;
