-- ── DATABASE SCHEMA FOR EDUFLEX ──────────────────────────────────────────────

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  display_name text,
  role text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Allow public read access for profiles"
  on public.profiles for select
  using (true);

create policy "Allow users to update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Allow admins to update all profiles"
  on public.profiles for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Trigger function to automatically create a profile on user sign up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'student')
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger on auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. COURSES TABLE
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  description text,
  category text,
  price integer not null default 0,
  duration_hours integer not null default 0,
  level text not null default 'debutant',
  image_url text,
  status text not null default 'publie',
  students_count integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for courses
alter table public.courses enable row level security;

-- Policies for courses
create policy "Allow public read access for courses"
  on public.courses for select
  using (true);

create policy "Allow authenticated users to insert courses"
  on public.courses for insert
  with check (auth.uid() = user_id);

create policy "Allow owners to update their courses"
  on public.courses for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Allow owners to delete their courses"
  on public.courses for delete
  using (auth.uid() = user_id);


-- 3. CHAPTERS TABLE
create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  content text,
  video_url text,
  sort_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for chapters
alter table public.chapters enable row level security;

-- Policies for chapters
create policy "Allow public read access for chapters"
  on public.chapters for select
  using (true);

create policy "Allow course owners to write chapters"
  on public.chapters for all
  using (
    exists (
      select 1 from public.courses
      where id = course_id and user_id = auth.uid()
    )
  );


-- 4. ENROLLMENTS TABLE
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  course_id bigint not null references public.courses(id) on delete cascade,
  progress_percent integer not null default 0,
  enrolled_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, course_id)
);

-- Enable Row Level Security (RLS) for enrollments
alter table public.enrollments enable row level security;

-- Policies for enrollments
create policy "Allow users to read their own enrollments"
  on public.enrollments for select
  using (auth.uid() = user_id);

create policy "Allow users to enroll themselves"
  on public.enrollments for insert
  with check (auth.uid() = user_id);

create policy "Allow users to update their own progress"
  on public.enrollments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- 5. COMPLETED CHAPTERS TABLE (For precise progress tracking)
create table if not exists public.completed_chapters (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  course_id bigint not null references public.courses(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, chapter_id)
);

-- Enable Row Level Security (RLS) for completed_chapters
alter table public.completed_chapters enable row level security;

-- Policies for completed_chapters
create policy "Allow users to read their own completions"
  on public.completed_chapters for select
  using (auth.uid() = user_id);

-- Let users insert or delete completions for themselves
create policy "Allow users to modify their own completions"
  on public.completed_chapters for all
  using (auth.uid() = user_id);


-- 6. PROGRESS TRIGGER (Calculates progression based on completed chapters)
create or replace function public.calculate_enrollment_progress()
returns trigger as $$
declare
  v_user_id uuid;
  v_course_id bigint;
  v_total_chapters integer;
  v_completed_chapters integer;
  v_progress integer;
begin
  if (TG_OP = 'DELETE') then
    v_user_id := old.user_id;
    v_course_id := old.course_id;
  else
    v_user_id := new.user_id;
    v_course_id := new.course_id;
  end if;

  -- Count total chapters
  select count(*) into v_total_chapters
  from public.chapters
  where course_id = v_course_id;

  -- Count completed chapters
  select count(*) into v_completed_chapters
  from public.completed_chapters
  where user_id = v_user_id and course_id = v_course_id;

  -- Calculate percentage
  if v_total_chapters > 0 then
    v_progress := (v_completed_chapters * 100) / v_total_chapters;
  else
    v_progress := 0;
  end if;

  -- Update enrollment progress
  update public.enrollments
  set progress_percent = v_progress
  where user_id = v_user_id and course_id = v_course_id;

  return null;
end;
$$ language plpgsql security definer;

-- Trigger on completed_chapters
create or replace trigger on_chapter_completion_change
  after insert or delete on public.completed_chapters
  for each row execute procedure public.calculate_enrollment_progress();


-- 7. SEED INITIAL COURSES DATA
insert into public.courses (id, user_id, title, description, category, price, duration_hours, level, image_url, status, students_count)
values
  (
    1,
    '00000000-0000-0000-0000-000000000000',
    'Marketing Digital de A à Z',
    'Maîtrisez les leviers du marketing digital : SEO, SEA, Social Media, Emailing et Analytics pour booster votre activité.',
    'Marketing',
    29900,
    25,
    'debutant',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=60',
    'publie',
    145
  ),
  (
    2,
    '00000000-0000-0000-0000-000000000000',
    'Business Management & Stratégie',
    'Apprenez à piloter une entreprise, définir une stratégie de croissance et manager vos équipes avec succès.',
    'Business',
    49900,
    40,
    'intermediaire',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=60',
    'publie',
    89
  ),
  (
    3,
    '00000000-0000-0000-0000-000000000000',
    'SEO & Création de Contenu',
    'Devenez visible sur Google. Techniques de référencement naturel avancées et rédaction de contenu engageant.',
    'Marketing',
    39900,
    15,
    'intermediaire',
    'https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=800&auto=format&fit=crop&q=60',
    'publie',
    210
  ),
  (
    4,
    '00000000-0000-0000-0000-000000000000',
    'Excel Avancé : Tableaux & Analyse',
    'Maîtrisez les formules complexes, les TCD, les macros VBA et la visualisation de données sur Microsoft Excel.',
    'Productivité',
    19900,
    12,
    'avance',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60',
    'publie',
    324
  )
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  duration_hours = excluded.duration_hours,
  level = excluded.level,
  image_url = excluded.image_url;

-- Seed some chapters for the first course
insert into public.chapters (course_id, title, content, video_url, sort_order)
values
  (1, 'Introduction au Marketing Digital', 'Dans ce chapitre, nous allons définir ce qu''est le marketing digital et présenter les différents canaux.', 'https://www.w3schools.com/html/mov_bbb.mp4', 1),
  (1, 'Les fondamentaux du SEO', 'Le référencement naturel (SEO) est l''art de positionner son site dans les premiers résultats de recherche.', null, 2),
  (1, 'Google Ads & Search Engine Marketing', 'Apprenez à configurer votre première campagne publicitaire payante sur Google Ads.', null, 3),
  (1, 'Stratégie de newsletter et emailing', 'L''emailing reste le canal avec le meilleur retour sur investissement. Voici comment créer une liste d''abonnés.', null, 5)
on conflict do nothing;

-- 8. PREMIUM FEATURES (QUIZ & PROMO CODES)
-- Add quiz_data column in chapters table
alter table public.chapters add column if not exists quiz_data jsonb default null;

-- Create promo_codes table
create table if not exists public.promo_codes (
  code text primary key,
  discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for promo_codes
alter table public.promo_codes enable row level security;

-- Policies for promo_codes
create policy "Allow public read access for promo codes"
  on public.promo_codes for select
  using (true);

-- Seed initial promo codes
insert into public.promo_codes (code, discount_percent, is_active)
values
  ('EDUFLEX20', 20, true),
  ('START50', 50, true)
on conflict (code) do nothing;

-- 9. PHASE 4 FEATURES (AFFILIATION & CHAPTER COMMENTS)
-- Create affiliate_referrals table
create table if not exists public.affiliate_referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid references public.profiles(id) on delete cascade,
  referred_email text not null,
  course_id bigint references public.courses(id) on delete cascade,
  commission_amount integer not null default 0, -- en centimes d'Euros (ex: 15% du prix de vente)
  status text not null default 'en_attente' check (status in ('en_attente', 'paye', 'annule')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for affiliate_referrals
alter table public.affiliate_referrals enable row level security;

-- Policies for affiliate_referrals
create policy "Allow users to read their own referrals"
  on public.affiliate_referrals for select
  using (auth.uid() = referrer_id);

create policy "Allow public insert for referrals"
  on public.affiliate_referrals for insert
  with check (true);

-- Create chapter_comments table
create table if not exists public.chapter_comments (
  id bigint generated by default as identity primary key,
  chapter_id bigint references public.chapters(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for chapter_comments
alter table public.chapter_comments enable row level security;

-- Policies for chapter_comments
create policy "Allow public read access for comments"
  on public.chapter_comments for select
  using (true);

create policy "Allow authenticated users to insert comments"
  on public.chapter_comments for insert
  with check (auth.uid() = user_id);

-- 10. PAYOUT REQUESTS (Option A of Payout & revenue management)
-- Create payout_requests table
create table if not exists public.payout_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  amount integer not null, -- en centimes
  payment_details text not null, -- numéro Mobile Money ou compte bancaire
  status text not null default 'en_attente' check (status in ('en_attente', 'valide', 'rejete')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.payout_requests enable row level security;

-- Policies for payout_requests
create policy "Allow users to read their own payout requests"
  on public.payout_requests for select
  using (auth.uid() = user_id or exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  ));

create policy "Allow users to insert their own payout requests"
  on public.payout_requests for insert
  with check (auth.uid() = user_id);

create policy "Allow admins to update payout requests"
  on public.payout_requests for update
  using (exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  ));

-- 11. B2B SCHOOL & ACADEMY EXTENSIONS
-- Alter chapters table to add types and livestream scheduled targets
alter table public.chapters add column if not exists chapter_type text default 'standard' check (chapter_type in ('standard', 'quiz', 'live'));
alter table public.chapters add column if not exists scheduled_at timestamp with time zone default null;
alter table public.chapters add column if not exists live_url text default null;

-- Alter profiles table to add school customization attributes
alter table public.profiles add column if not exists academy_name text default null;
alter table public.profiles add column if not exists academy_slogan text default null;
alter table public.profiles add column if not exists academy_color text default '#6366f1';
alter table public.profiles add column if not exists approved boolean not null default true;
alter table public.profiles add column if not exists academy_plan text default 'Découverte';
alter table public.profiles add column if not exists academy_logo text default null;


