/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EduflexPlusRouteImport } from './routes/eduflex-plus'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStatistiquesRouteImport } from './routes/_app/statistiques'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPaiementsRouteImport } from './routes/_app/paiements'
import { Route as AppManageCoursesRouteImport } from './routes/_app/manage-courses'
import { Route as AppEnseignantsRouteImport } from './routes/_app/enseignants'
import { Route as AppElevesRouteImport } from './routes/_app/eleves'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppAcademiesRouteImport } from './routes/_app/academies'
import { Route as AppStudyIdRouteImport } from './routes/_app/study.$id'
import { Route as AppCoursesIdRouteImport } from './routes/_app/courses.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EduflexPlusRoute = EduflexPlusRouteImport.update({
  id: '/eduflex-plus',
  path: '/eduflex-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatistiquesRoute = AppStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaiementsRoute = AppPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AppRoute,
} as any)
const AppManageCoursesRoute = AppManageCoursesRouteImport.update({
  id: '/manage-courses',
  path: '/manage-courses',
  getParentRoute: () => AppRoute,
} as any)
const AppEnseignantsRoute = AppEnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => AppRoute,
} as any)
const AppElevesRoute = AppElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademiesRoute = AppAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyIdRoute = AppStudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIdRoute = AppCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/academies': typeof AppAcademiesRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/eleves': typeof AppElevesRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/manage-courses': typeof AppManageCoursesRoute
  '/paiements': typeof AppPaiementsRoute
  '/settings': typeof AppSettingsRoute
  '/statistiques': typeof AppStatistiquesRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/study/$id': typeof AppStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/academies': typeof AppAcademiesRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/eleves': typeof AppElevesRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/manage-courses': typeof AppManageCoursesRoute
  '/paiements': typeof AppPaiementsRoute
  '/settings': typeof AppSettingsRoute
  '/statistiques': typeof AppStatistiquesRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/study/$id': typeof AppStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/academies': typeof AppAcademiesRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eleves': typeof AppElevesRoute
  '/_app/enseignants': typeof AppEnseignantsRoute
  '/_app/manage-courses': typeof AppManageCoursesRoute
  '/_app/paiements': typeof AppPaiementsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statistiques': typeof AppStatistiquesRoute
  '/_app/courses/$id': typeof AppCoursesIdRoute
  '/_app/study/$id': typeof AppStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/academies'
    | '/courses'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/manage-courses'
    | '/paiements'
    | '/settings'
    | '/statistiques'
    | '/courses/$id'
    | '/study/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/academies'
    | '/courses'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/manage-courses'
    | '/paiements'
    | '/settings'
    | '/statistiques'
    | '/courses/$id'
    | '/study/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/_app/academies'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/eleves'
    | '/_app/enseignants'
    | '/_app/manage-courses'
    | '/_app/paiements'
    | '/_app/settings'
    | '/_app/statistiques'
    | '/_app/courses/$id'
    | '/_app/study/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EduflexPlusRoute: typeof EduflexPlusRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eduflex-plus': {
      id: '/eduflex-plus'
      path: '/eduflex-plus'
      fullPath: '/eduflex-plus'
      preLoaderRoute: typeof EduflexPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/statistiques': {
      id: '/_app/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AppStatistiquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paiements': {
      id: '/_app/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AppPaiementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-courses': {
      id: '/_app/manage-courses'
      path: '/manage-courses'
      fullPath: '/manage-courses'
      preLoaderRoute: typeof AppManageCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enseignants': {
      id: '/_app/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AppEnseignantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleves': {
      id: '/_app/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AppElevesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academies': {
      id: '/_app/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AppAcademiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study/$id': {
      id: '/_app/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof AppStudyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$id': {
      id: '/_app/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AppCoursesIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesIdRoute: typeof AppCoursesIdRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesIdRoute: AppCoursesIdRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRouteChildren {
  AppAcademiesRoute: typeof AppAcademiesRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppElevesRoute: typeof AppElevesRoute
  AppEnseignantsRoute: typeof AppEnseignantsRoute
  AppManageCoursesRoute: typeof AppManageCoursesRoute
  AppPaiementsRoute: typeof AppPaiementsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatistiquesRoute: typeof AppStatistiquesRoute
  AppStudyIdRoute: typeof AppStudyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademiesRoute: AppAcademiesRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppElevesRoute: AppElevesRoute,
  AppEnseignantsRoute: AppEnseignantsRoute,
  AppManageCoursesRoute: AppManageCoursesRoute,
  AppPaiementsRoute: AppPaiementsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatistiquesRoute: AppStatistiquesRoute,
  AppStudyIdRoute: AppStudyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EduflexPlusRoute: EduflexPlusRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
