/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EduflexPlusRouteImport } from './routes/eduflex-plus'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStatistiquesRouteImport } from './routes/_app/statistiques'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPaiementsRouteImport } from './routes/_app/paiements'
import { Route as AppPacksRouteImport } from './routes/_app/packs'
import { Route as AppOutilsMarketingRouteImport } from './routes/_app/outils-marketing'
import { Route as AppManageCoursesRouteImport } from './routes/_app/manage-courses'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppEnseignantsRouteImport } from './routes/_app/enseignants'
import { Route as AppElevesRouteImport } from './routes/_app/eleves'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCommunauteRouteImport } from './routes/_app/communaute'
import { Route as AppCodesPromoRouteImport } from './routes/_app/codes-promo'
import { Route as AppClassesVirtuellesRouteImport } from './routes/_app/classes-virtuelles'
import { Route as AppCalendrierRouteImport } from './routes/_app/calendrier'
import { Route as AppAssistantsIaRouteImport } from './routes/_app/assistants-ia'
import { Route as AppAffiliationRouteImport } from './routes/_app/affiliation'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin-settings'
import { Route as AppAcademyHubRouteImport } from './routes/_app/academy-hub'
import { Route as AppAcademiesRouteImport } from './routes/_app/academies'
import { Route as AppStudyIdRouteImport } from './routes/_app/study.$id'
import { Route as AppCoursesIdRouteImport } from './routes/_app/courses.$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EduflexPlusRoute = EduflexPlusRouteImport.update({
  id: '/eduflex-plus',
  path: '/eduflex-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatistiquesRoute = AppStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaiementsRoute = AppPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AppRoute,
} as any)
const AppPacksRoute = AppPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AppRoute,
} as any)
const AppOutilsMarketingRoute = AppOutilsMarketingRouteImport.update({
  id: '/outils-marketing',
  path: '/outils-marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppManageCoursesRoute = AppManageCoursesRouteImport.update({
  id: '/manage-courses',
  path: '/manage-courses',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppEnseignantsRoute = AppEnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => AppRoute,
} as any)
const AppElevesRoute = AppElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunauteRoute = AppCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => AppRoute,
} as any)
const AppCodesPromoRoute = AppCodesPromoRouteImport.update({
  id: '/codes-promo',
  path: '/codes-promo',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesVirtuellesRoute = AppClassesVirtuellesRouteImport.update({
  id: '/classes-virtuelles',
  path: '/classes-virtuelles',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendrierRoute = AppCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantsIaRoute = AppAssistantsIaRouteImport.update({
  id: '/assistants-ia',
  path: '/assistants-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliationRoute = AppAffiliationRouteImport.update({
  id: '/affiliation',
  path: '/affiliation',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyHubRoute = AppAcademyHubRouteImport.update({
  id: '/academy-hub',
  path: '/academy-hub',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademiesRoute = AppAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyIdRoute = AppStudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIdRoute = AppCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tarifs': typeof TarifsRoute
  '/academies': typeof AppAcademiesRoute
  '/academy-hub': typeof AppAcademyHubRoute
  '/admin-settings': typeof AppAdminSettingsRoute
  '/affiliation': typeof AppAffiliationRoute
  '/assistants-ia': typeof AppAssistantsIaRoute
  '/calendrier': typeof AppCalendrierRoute
  '/classes-virtuelles': typeof AppClassesVirtuellesRoute
  '/codes-promo': typeof AppCodesPromoRoute
  '/communaute': typeof AppCommunauteRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/eleves': typeof AppElevesRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/manage-courses': typeof AppManageCoursesRoute
  '/outils-marketing': typeof AppOutilsMarketingRoute
  '/packs': typeof AppPacksRoute
  '/paiements': typeof AppPaiementsRoute
  '/settings': typeof AppSettingsRoute
  '/statistiques': typeof AppStatistiquesRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/study/$id': typeof AppStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tarifs': typeof TarifsRoute
  '/academies': typeof AppAcademiesRoute
  '/academy-hub': typeof AppAcademyHubRoute
  '/admin-settings': typeof AppAdminSettingsRoute
  '/affiliation': typeof AppAffiliationRoute
  '/assistants-ia': typeof AppAssistantsIaRoute
  '/calendrier': typeof AppCalendrierRoute
  '/classes-virtuelles': typeof AppClassesVirtuellesRoute
  '/codes-promo': typeof AppCodesPromoRoute
  '/communaute': typeof AppCommunauteRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/eleves': typeof AppElevesRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/manage-courses': typeof AppManageCoursesRoute
  '/outils-marketing': typeof AppOutilsMarketingRoute
  '/packs': typeof AppPacksRoute
  '/paiements': typeof AppPaiementsRoute
  '/settings': typeof AppSettingsRoute
  '/statistiques': typeof AppStatistiquesRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/study/$id': typeof AppStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/eduflex-plus': typeof EduflexPlusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tarifs': typeof TarifsRoute
  '/_app/academies': typeof AppAcademiesRoute
  '/_app/academy-hub': typeof AppAcademyHubRoute
  '/_app/admin-settings': typeof AppAdminSettingsRoute
  '/_app/affiliation': typeof AppAffiliationRoute
  '/_app/assistants-ia': typeof AppAssistantsIaRoute
  '/_app/calendrier': typeof AppCalendrierRoute
  '/_app/classes-virtuelles': typeof AppClassesVirtuellesRoute
  '/_app/codes-promo': typeof AppCodesPromoRoute
  '/_app/communaute': typeof AppCommunauteRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eleves': typeof AppElevesRoute
  '/_app/enseignants': typeof AppEnseignantsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/manage-courses': typeof AppManageCoursesRoute
  '/_app/outils-marketing': typeof AppOutilsMarketingRoute
  '/_app/packs': typeof AppPacksRoute
  '/_app/paiements': typeof AppPaiementsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statistiques': typeof AppStatistiquesRoute
  '/_app/courses/$id': typeof AppCoursesIdRoute
  '/_app/study/$id': typeof AppStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/tarifs'
    | '/academies'
    | '/academy-hub'
    | '/admin-settings'
    | '/affiliation'
    | '/assistants-ia'
    | '/calendrier'
    | '/classes-virtuelles'
    | '/codes-promo'
    | '/communaute'
    | '/courses'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/integrations'
    | '/manage-courses'
    | '/outils-marketing'
    | '/packs'
    | '/paiements'
    | '/settings'
    | '/statistiques'
    | '/courses/$id'
    | '/study/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/tarifs'
    | '/academies'
    | '/academy-hub'
    | '/admin-settings'
    | '/affiliation'
    | '/assistants-ia'
    | '/calendrier'
    | '/classes-virtuelles'
    | '/codes-promo'
    | '/communaute'
    | '/courses'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/integrations'
    | '/manage-courses'
    | '/outils-marketing'
    | '/packs'
    | '/paiements'
    | '/settings'
    | '/statistiques'
    | '/courses/$id'
    | '/study/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/eduflex-plus'
    | '/login'
    | '/register'
    | '/tarifs'
    | '/_app/academies'
    | '/_app/academy-hub'
    | '/_app/admin-settings'
    | '/_app/affiliation'
    | '/_app/assistants-ia'
    | '/_app/calendrier'
    | '/_app/classes-virtuelles'
    | '/_app/codes-promo'
    | '/_app/communaute'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/eleves'
    | '/_app/enseignants'
    | '/_app/integrations'
    | '/_app/manage-courses'
    | '/_app/outils-marketing'
    | '/_app/packs'
    | '/_app/paiements'
    | '/_app/settings'
    | '/_app/statistiques'
    | '/_app/courses/$id'
    | '/_app/study/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EduflexPlusRoute: typeof EduflexPlusRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eduflex-plus': {
      id: '/eduflex-plus'
      path: '/eduflex-plus'
      fullPath: '/eduflex-plus'
      preLoaderRoute: typeof EduflexPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/statistiques': {
      id: '/_app/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AppStatistiquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paiements': {
      id: '/_app/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AppPaiementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packs': {
      id: '/_app/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AppPacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outils-marketing': {
      id: '/_app/outils-marketing'
      path: '/outils-marketing'
      fullPath: '/outils-marketing'
      preLoaderRoute: typeof AppOutilsMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-courses': {
      id: '/_app/manage-courses'
      path: '/manage-courses'
      fullPath: '/manage-courses'
      preLoaderRoute: typeof AppManageCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enseignants': {
      id: '/_app/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AppEnseignantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleves': {
      id: '/_app/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AppElevesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communaute': {
      id: '/_app/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof AppCommunauteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/codes-promo': {
      id: '/_app/codes-promo'
      path: '/codes-promo'
      fullPath: '/codes-promo'
      preLoaderRoute: typeof AppCodesPromoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes-virtuelles': {
      id: '/_app/classes-virtuelles'
      path: '/classes-virtuelles'
      fullPath: '/classes-virtuelles'
      preLoaderRoute: typeof AppClassesVirtuellesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendrier': {
      id: '/_app/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AppCalendrierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistants-ia': {
      id: '/_app/assistants-ia'
      path: '/assistants-ia'
      fullPath: '/assistants-ia'
      preLoaderRoute: typeof AppAssistantsIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliation': {
      id: '/_app/affiliation'
      path: '/affiliation'
      fullPath: '/affiliation'
      preLoaderRoute: typeof AppAffiliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-settings': {
      id: '/_app/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academy-hub': {
      id: '/_app/academy-hub'
      path: '/academy-hub'
      fullPath: '/academy-hub'
      preLoaderRoute: typeof AppAcademyHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academies': {
      id: '/_app/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AppAcademiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study/$id': {
      id: '/_app/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof AppStudyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$id': {
      id: '/_app/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AppCoursesIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesIdRoute: typeof AppCoursesIdRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesIdRoute: AppCoursesIdRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRouteChildren {
  AppAcademiesRoute: typeof AppAcademiesRoute
  AppAcademyHubRoute: typeof AppAcademyHubRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAffiliationRoute: typeof AppAffiliationRoute
  AppAssistantsIaRoute: typeof AppAssistantsIaRoute
  AppCalendrierRoute: typeof AppCalendrierRoute
  AppClassesVirtuellesRoute: typeof AppClassesVirtuellesRoute
  AppCodesPromoRoute: typeof AppCodesPromoRoute
  AppCommunauteRoute: typeof AppCommunauteRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppElevesRoute: typeof AppElevesRoute
  AppEnseignantsRoute: typeof AppEnseignantsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppManageCoursesRoute: typeof AppManageCoursesRoute
  AppOutilsMarketingRoute: typeof AppOutilsMarketingRoute
  AppPacksRoute: typeof AppPacksRoute
  AppPaiementsRoute: typeof AppPaiementsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatistiquesRoute: typeof AppStatistiquesRoute
  AppStudyIdRoute: typeof AppStudyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademiesRoute: AppAcademiesRoute,
  AppAcademyHubRoute: AppAcademyHubRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAffiliationRoute: AppAffiliationRoute,
  AppAssistantsIaRoute: AppAssistantsIaRoute,
  AppCalendrierRoute: AppCalendrierRoute,
  AppClassesVirtuellesRoute: AppClassesVirtuellesRoute,
  AppCodesPromoRoute: AppCodesPromoRoute,
  AppCommunauteRoute: AppCommunauteRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppElevesRoute: AppElevesRoute,
  AppEnseignantsRoute: AppEnseignantsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppManageCoursesRoute: AppManageCoursesRoute,
  AppOutilsMarketingRoute: AppOutilsMarketingRoute,
  AppPacksRoute: AppPacksRoute,
  AppPaiementsRoute: AppPaiementsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatistiquesRoute: AppStatistiquesRoute,
  AppStudyIdRoute: AppStudyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EduflexPlusRoute: EduflexPlusRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
